apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-auto-encrypted
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp2
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-auto
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp2
  encrypted: "false"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-auto-encrypted
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-auto
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "false"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
