apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ingress-nginx-vpa
  namespace: ingress-nginx
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "ingress-nginx-controller"
    # Note: This is more stable compared to HPA, which may not be as reliable.
    # Additionally, this approach helps reduce latency for ingress-nginx (same as ingress-nginx-hpa) and is more effective in preventing NGINX bottlenecks.
    # When NGINX becomes a bottleneck, its memory usage increases, indicating that the target deployment (not the NGINX deployment) cannot handle high traffic or a large number of requests.
      minAllowed:
        cpu: 50m
        memory: 50Mi
      maxAllowed:
        cpu: 2
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
