# REST API Ingress Controller Configuration [Zer0 Downtime].
# Note: This suitable for fiber that in internal mode (e.g, private cluster, never exposed to service)
apiVersion: v1
data:
  allow-snippet-annotations: "true" # Enable snippet annotations
  hsts: "false" # for rest api this not really important, so disabled
  log-format-upstream:
    '[H0llyW00dzZ Network] [Operator: $namespace - $ingress_name - $service_name] $remote_addr - $remote_user [Cloudflare: Client IP: $http_cf_connecting_ip - Country: $http_cf_ipcountry] [Cloudflare Worker: $http_cf_worker] [$time_local] "$request" $status $body_bytes_sent
    "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name]
    [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time
    $upstream_status $req_id'
  ssl-protocols: TLSv1.3
  use-upstream-server-addr: "true" # pretty useful for communication through internal mode (e.g, private cluster, never exposed to service)
  generate-request-id: "false" # disable default nginx request-id generation as it is already handled by the fiber framework
  server-tokens: "false" # Disable the default Server header
  enable-brotli: "true" # Enhance speed for CompressJSON, by default this false
  brotli-level: "6" # Perfectly balanced for resource (cpu, memory)
  brotli-min-length: "200" # Same As Brotli Compress Fiber Framework
  server-snippet: |
    more_set_headers "Server: H0llyW00dzZ Network";
    more_set_headers "Via: H0llyW00dzZ Network";
  enable-ocsp: "true" # Enable HIPAA (https://www.hhs.gov/hipaa/for-professionals/security/guidance/index.html) and NIST (https://csrc.nist.gov/glossary/term/online_certificate_status_protocol) Compliance Test
  proxy-buffering: "on" # which is suitable for handling AI
kind: ConfigMap
# When this is applied, it will configure the ingress-nginx-controller for smooth sailing ⛵ ☸
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
