# REST API Ingress Controller Configuration [Zer0 Downtime].
# Note: This suitable for fiber that in internal mode (e.g, private cluster, never exposed to service)
apiVersion: v1
data:
  allow-snippet-annotations: "false"
  hsts: "false" # for rest api this not really important, so disabled
  log-format-upstream:
    '[H0llyW00dzZ Network] $remote_addr - $remote_user [Cloudflare: Client IP: $http_cf_connecting_ip - Country: $http_cf_ipcountry] [Cloudflare Worker: $http_cf_worker] [$time_local] "$request" $status $body_bytes_sent
    "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name]
    [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time
    $upstream_status $req_id'
  ssl-protocols: TLSv1.3
  use-upstream-server-addr: "true" # pretty useful for communication through internal mode (e.g, private cluster, never exposed to service)
  generate-request-id: "false" # disable default nginx request-id generation as it is already handled by the fiber framework
kind: ConfigMap
name: ingress-nginx-controller # this optional due it can be customized, basically it just reference before sailing
namespace: ingress-nginx # this optional due it can be customized, basically it just reference before sailing
