# REST API Ingress Controller Configuration [Zer0 Downtime].
apiVersion: v1
data:
  allow-snippet-annotations: "false"
  hsts: "false"
  log-format-upstream:
    '[H0llyW00dzZ Network] $remote_addr - $remote_user [Cloudflare: Client IP: $http_cf_connecting_ip - Country: $http_cf_ipcountry] [Cloudflare Worker: $http_cf_worker] [$time_local] "$request" $status $body_bytes_sent
    "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name]
    [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time
    $upstream_status $req_id'
  ssl-protocols: TLSv1.3
  use-upstream-server-addr: "true"
kind: ConfigMap
