# MySQL Storage for MySQL Deployment [Zero Downtime] by H0llyW00dzZ for a microservices Kubernetes cluster.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  namespace: database
spec:
  accessModes:
    # Note: This is suitable for a VPA with "ReadWriteOnce" access mode and a minimum of 1 replica for VPA. 
    # Unlike RWX, which makes it possible to achieve zero downtime, RWO does not allow for zero-downtime scaling.
    # However, RWX is rarely supported by some cloud providers.
    - ReadWriteOnce
  storageClassName: gp2-encrypted
  resources:
    requests:
      # Note: This can be customized based on the storage requirements needed for storing all MySQL data.
      storage: 100Gi
