apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coredns
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns
  minReplicas: 2
  # Note: Adjust as needed; however, a maxReplicas of 6 with avg 80% is usually sufficient.
  # For nodes dedicated to critical Kubernetes components with a capacity of 8 to 16 CPUs or more, 
  # it is recommended to adjust the settings to 50 or 100.
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
