# Note: When using CoreDNS with HPA, it is not recommended to use DNS local caching.
# Misconfiguration DNS local caching can lead to significant issues (e.g., can lead to stale DNS entries and connectivity problems).
# Additionally, this can improve latency, as it can be synchronized with other HPA deployments (e.g., this repo REST APIs).
# Average latency (regional):
# ;; Query time: 30msec ~ ;; Query time: 10msec
#
# Note that achieving average latency across multiple regions (global) is possible, but it is quite complex.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coredns
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns
  minReplicas: 2
  # Note: Adjust as needed; however, a maxReplicas of 6 with avg 80% is usually sufficient.
  # For nodes dedicated to critical Kubernetes components with a capacity of 8 to 16 CPUs or more, 
  # it is recommended to adjust the settings to 50 ~ 100 or max (e.g., 99999999999999).
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
