# Build and Push Docker Image to Private Registry by H0llyW00dzZ
#
# Note: This is a boilerplate CI/CD. You need to modify the registry "example.com".
# Also note that this is different from "gcloud-builds.yaml" because "gcloud-builds.yaml" involves remote builds, 
# which means you must monitor the build until it completes. If you terminate the process during a build using "gcloud-builds.yaml", it will cancel the build.
#
# Compatibility:
# This supports any Git code hosting platform. For example, it works with Gitea, which I personally use for GitOps, DevOps, and DevSecOps on my Kubernetes cluster.
# However, if you are using GitHub with a private repository, you need to modify this CI/CD process by removing the cache after building.
# It also supports any private registry implementation. For example, if you want to manage your own private registry, it is supported.
#
# Tips:
# For runners on Kubernetes, you need to build the container from this repository: https://git.b0zal.io/H0llyW00dzZ/act_runner (a mirror of https://gitea.com/gitea/act_runner.git).
# If you're unsure how to build the container for the runner, it's better to use a VM/KVM. If you're on bare metal, it's recommended to use a VM/KVM as well.
name: Build and Push Docker Image to Private Registry

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Private Registry
        uses: docker/login-action@v2
        with:
          # Note: Don't forget to modify "example.com"
          registry: example.com
          # Note: The username depends on the private registry implementation. It can be a username or an email.
          username: ${{ secrets.ACC_EMAIL }}
          # Note: The password depends on the private registry implementation. It can be a token, API key, or an actual password.
          password: ${{ secrets.PASSWORD_REGISTRY }}

      - name: Build and push Docker image to Private Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Note: Don't forget to modify "example.com"
          tags: |
            example.com/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}
            example.com/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:latest
